server:
  error:
    include-exception: true
    include-message: ALWAYS
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: P@ssw0rd123
    url: jdbc:mysql://localhost:3306/budgetapp?SSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
  
